version: "3.8"
services:
  database:
    image: mysql:5.7
    container_name: database
    # volumes:
      # - .docker/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/usr/share/nginx
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - database
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/src:/usr/server/src
    env_file:
      - .env
    ports:
      - "3001:3000"
    depends_on:
      - backend